### ISSUE TITLE
Release 2.0.10 deployment target should be iOS 8.0

### ISSUE THREAD

**Issue by jameszoh** [andreamazz/AMScrollingNavbar#176] opened 2016-01-06 14:25 UTC
I rememeber 2.0.9 is target iOS 8.0. but 2.0.10 is target iOS 8.4.
`Module file's minimum deployment target is ios8.4 v8.4: /App/AMScrollingNavbar.framework/Modules/AMScrollingNavbar.swiftmodule/x86_64.swiftmodule`

**Comment by andreamazz** [comment] 2016-01-06 14:30
I'm not sure why. How are you installing this framework? Carthage?

**Comment by jameszoh** [comment] 2016-01-06 14:35
2.0.9 is working fine. when i switch to 2.0.10, the error showed up.
I followed the same way when i install 2.0.9: by adding **Embedded Binaries**. nothing more

**Comment by andreamazz** [comment] 2016-01-06 15:57
This is odd, the project still is on target 8.0. I tried to rebuild the framework, and updated the release. Let me know if it's working now.

**Comment by jameszoh** [comment] 2016-01-06 20:46
tried! but the same problem still exists. any clue?

**Comment by andreamazz** [comment] 2016-01-06 20:49
Not really. The only thing changed seems to be the Carthage version used. You can try to build the framework on your own (just clone and build the project in the root) or try to integrate it with CocoaPods.

**Comment by ryancrunchi** [comment] 2016-02-10 17:53
Hi, thanks for your work. I have the same problem using cocoapods. My project has a deployment target set to 8.0 and running `pod install` outputs
`[!] Unable to satisfy the following requirements:

- "AMScrollingNavbar (~> 2.0)" required by "Podfile"

Specs satisfying the "AMScrollingNavbar (~> 2.0)" dependency were found, but they required a higher minimum deployment target.`

**Comment by andreamazz** [comment] 2016-02-22 19:39
That's weird, the pod target is 8.0.
Let me check

**Comment by andreamazz** [comment] 2016-02-22 19:41
Just tested with a new project with a 8.0 target, and works fine.

**Comment by ffittschen** [comment] 2016-02-26 10:09
After updating from `2.0.10` to `2.0.11` I get this error message as well.

**Comment by andreamazz** [comment] 2016-02-26 10:10
Which CocoaPods version are you using?

**Comment by ffittschen** [comment] 2016-02-26 10:11
@andreamazz I'm using Carthage 0.14.0

**Comment by ffittschen** [comment] 2016-02-26 10:15
Could it be that the Deployment target is not resolving correctly?

<img width="1142" alt="screen shot 2016-02-26 at 11 14 41" src="https://cloud.githubusercontent.com/assets/7734806/13349451/2ded60dc-dc7a-11e5-9097-6d6e1f132eb7.png">

**Comment by andreamazz** [comment] 2016-02-26 10:19
The resolved target looks fine. Did you try to embed the prebuilt library manually? https://github.com/andreamazz/AMScrollingNavbar/releases/tag/2.0.11
It was built with carthage `0.10.0`, maybe I just need to update it.

**Comment by ffittschen** [comment] 2016-02-26 10:24
I just replaced it with the prebuilt library: same error

**Comment by ffittschen** [comment] 2016-02-26 10:52
I was also wondering why carthage is building `AMScrollingNavbar` twice, so I just looked into the build log. There it says it is building the `Pods` target (which has a deployment target of 8.4  🎉😄)!
`=== BUILD TARGET AMScrollingNavbar OF PROJECT Pods WITH CONFIGURATION Release ===`

So I went into the `Carthage/Checkout/AMScrollingNavbar` folder, deleted the `Demo` folder and ran `carthage build --platform iOS` again: 
`AMScrollingNavbar` is just built once again and the error is gone! :+1: 

I guess it should somehow be possible to tell `carthage` that it should not build the demo project

**Comment by andreamazz** [comment] 2016-02-26 10:57
Cool, thanks! I've attached a new prebuilt framework to the latest release, now it should work fine, I just tested it with a dummy project.

**Comment by alwaysthecritic** [comment] 2016-03-02 22:21
You'll be distressed to hear that I just added the framework to my project for the first time with Carthage, it picked up 2.0.11 but I ran into the exact same problem with it complaining about iOS 8.4 with the binary that Carthage downloads :-(

I note that I can workaround this somewhat by building my own version, having modified the Demo project's AMScrollingNavbar target to be 8.0 instead of 8.4.

Is this a regression for the 2.0.11 release in some weird way?

**Comment by andreamazz** [comment] 2016-03-04 11:25
Weird, 2.0.11 is the release that should fix this issue. I also changed the demo target. Let me double check.

**Comment by andreamazz** [comment] 2016-03-04 11:32
Try version `2.0.12`

**Comment by Venko132** [comment] 2016-03-04 11:52
Hi, I've got this issue in new demo project
/Users/user/Downloads/AMScrollingNavbar-master 4/Demo/ScrollingNavbarDemo/ViewController.swift:10:8: Module file's minimum deployment target is ios8.4 v8.4: /Users/user/Library/Developer/Xcode/DerivedData/ScrollingNavbarDemo-dxleddyedumtslhcwoyoprxdhunj/Build/Products/Debug-iphonesimulator/AMScrollingNavbar.framework/Modules/AMScrollingNavbar.swiftmodule/x86_64.swiftmodule

**Comment by alwaysthecritic** [comment] 2016-03-07 22:23
I'm afraid I'm not in a position to test this anymore as I've integrated the code directly into my project and modified it to suit my needs in various ways.

Thanks for this project though - it has helped me a lot!

**Comment by dacchan** [comment] 2016-03-08 05:55
I think `Pods` folder existing in `Demo` folder to be a cause of trouble.

It seems that `Carthage` builds a target of `AMScrollingNavbar` in `ScrollingNavbarDemo.xcworkspace (Pods.xcodeproj) ` side and `iOS Deployment Target` which is set as `MinimumOSVersion` in `Pods.xcodeproj`, is set as `AMScrollingNavbar.framework`.

After deleting the `Pods` folder for trial, `AMScrollingNavbar.framework` which is`MinimumOSVersion 8.0` was created.

**Comment by andreamazz** [comment] 2016-03-08 08:59
Tried to set the pods for the demo to target 8.0.
Try version `2.0.13` and let me know if this fixes this issue. Thanks :+1:

**Comment by dacchan** [comment] 2016-03-09 01:24
Thank you very much for your advice.

**Comment by andreamazz** [comment] 2016-03-24 09:51
Closing this, let me know if the issue persist in the latest release.

**Closed by andreamazz** 2016-03-24 09:51 UTC
