### ISSUE TITLE
A small blank in the top of the navigation bar

### ISSUE THREAD

**Issue by songhailiang** [andreamazz/AMScrollingNavbar#254] opened 2017-06-09 07:50 UTC
Hi,
Here I come again.
I found this issue in the demo project, i just changed the background color of the scrollview to white to check this issue more clearly.
When the navigation bar is .collapsed, there will be a small blank in the top of the navigation bar when the scrollView got a small scrolling. 
I think it's caused by the animation in ```checkForPartialScroll```. Is there a nice solution?

Here is a screenshot for you.
![scrollingnavbar](https://user-images.githubusercontent.com/11569411/26965594-0af33d74-4d29-11e7-90c4-e1810d7860ab.gif)

**Comment by andreamazz** [comment] 2017-06-09 07:53
Hi @songhailiang 
Yep, I noticed it too yesterday while fixing the other issue. This looks like a regression with the latest version of iOS, it was working previously 😭 
I'll see if I can find a workaround, any help is appreciated.

**Comment by songhailiang** [comment] 2017-06-16 05:53
How about this. I create an overlay view and add it to navigation bar to cover the blank. 
```
    let overlay = UIView()
    overlay.frame = navigationBar.bounds
    overlay.backgroundColor = navigationBar.barTintColor
    navigationBar.insertSubview(overlay, at: 0)

    UIView.animate(withDuration: duration, delay: 0, options: UIViewAnimationOptions.beginFromCurrentState, animations: {
      self.updateSizing(delta)
      self.updateFollowers(delta)
      self.updateNavbarAlpha()
    }, completion: {
      (finished) in
      overlay.removeFromSuperview()
    })
```

**Comment by abdurrahmansanli** [comment] 2017-08-09 11:05
That white area is the status bar. This library acts as one piece of view going up and down, it doesn't alter with the status bar. You can change status bar color manually to avoid that effect.

`UIApplication.shared.statusBarView?.backgroundColor = .red`

**Anyone who is experiencing this problem: set status bar color to the navigation bar color you like to use and it will be resolved.**

**Comment by andreamazz** [comment] 2017-12-19 17:41
This should be fixed, I can't reproduce it anymore. Feel free to reopen if needed.

**Closed by andreamazz** 2017-12-19 17:41 UTC
Labels: bug, help wanted
