### ISSUE TITLE
Strange black background

### ISSUE THREAD

**Issue by H3rrVorrag3nd** [andreamazz/AMScrollingNavbar#135] opened 2015-06-02 22:14 UTC
Hey,

I have a ViewController with a UIWebView and Navigation Bar.
Here is a GIF which should show you my problem (because it's kinda hard to explain):
https://drive.google.com/file/d/0B8r_MsK6ZHSWcHY5T0h1NkJxOWc/view

Picture 1:
I load a simple website

Picture 2:
I scroll down the website -> the Navbar hides as expected

Picture 3:
I rotate my iPad (the error only appears on iPad - not on iPhone!) so that I end up in landscape mode -> the Navbar is still hidden

Picture 4:
I scroll up a little bit, so the Navbar should become visible again. That works - but here is the problem, I suddenly have this black "field" there and I can't figure out why.

I did add the AMScrollingNavbar following the video tutorial and have these lines (which I think could be important to get an idea which setting could be wrong?) - and I'm using Auto Layout:
 
[self followScrollView:uiWebView usingTopConstraint:self.topConstraint withDelay:65];
[self setUseSuperview:NO];

Maybe someone can help me out..I'm running out of ideas.

**Comment by andreamazz** [comment] 2015-06-03 15:43
Hi @H3rrVorrag3nd 
I'll try to reproduce it and let you know as soon as possible.

**Comment by andreamazz** [comment] 2015-06-03 16:16
I can't reproduce the issue, can you provide a sample showing the issue?

**Comment by ryanchan002** [comment] 2015-06-05 18:04
Having the same issue here...

**Comment by andreamazz** [comment] 2015-06-06 12:28
Having a sample with the issue would help a lot, I can't reproduce it right now.

**Comment by H3rrVorrag3nd** [comment] 2015-06-07 21:13
I just used a simple sample and did upload it: https://github.com/H3rrVorrag3nd/AMNavTest

In my opinion I followed the integration tutorial the right way - but maybe I did something wrong.
Hope you can help me

**Comment by andreamazz** [comment] 2015-06-08 08:56
Ok I see, looks like it's an issue with the iPad only, with the iPhone the same code runs fine. huh

**Comment by H3rrVorrag3nd** [comment] 2015-06-08 14:00
Yep only an issue on iPad. Hope you can find a solution :)

**Comment by andreamazz** [comment] 2015-08-17 14:36
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146

**Comment by andreamazz** [comment] 2015-10-21 14:23
Reopening this, I'll work on this as soon as possible.

**Comment by andreamazz** [comment] 2015-10-23 14:12
<img width="1056" alt="screen shot 2015-10-23 at 15 51 02" src="https://cloud.githubusercontent.com/assets/570797/10694827/aad968bc-79a0-11e5-902f-5fc69044a99c.png">

Looks like a UIKit bug to me. The frame of the navigation bar is fine, the private UIImageView used to draw the background is rendered the wrong way.

**Comment by andreamazz** [comment] 2015-10-23 14:25
Ok, got this. It was tricky, I had to show the navbar *before* the rotation.

**Closed by andreamazz** 2015-10-23 14:25 UTC
Labels: bug, help wanted
