### ISSUE TITLE
Large Titles make the content disappear

### ISSUE THREAD

**Issue by L4grange** [andreamazz/AMScrollingNavbar#322] opened 2018-07-26 12:32 UTC
**Describe the bug**
Another bug I've found is with the large titles that are hiding the content. Please see the attached gif. Try the following on the sample project:

**To Reproduce**
1. Open the sample project and select Large Titles
2. Scroll down
3. Scroll all the way up
4. The Content is now hidden under the large Navigaiton Bar.

**Expected behavior**
The content offset should not change, and the whole contents of the scroll view should remain visible.

**Screenshots**
Please see the video of the problem: [gif](https://imgur.com/39rp7Lc)

**Comment by andreamazz** [comment] 2018-07-26 15:05
The issue is [here](https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L424).  
At the moment I can't come up with a solution, however, if you don't need a table view with a floating header, you can comment out that line.

**Comment by L4grange** [comment] 2018-07-26 15:14
I'm trying to get a CollectionView with a large title, but for now I;ve disabled the AMScrollingNavBar for that ViewController. Thanks for pointing this out!

**Comment by StefaniOSApps** [comment] 2018-10-17 09:11
this bug was fixed in my pull request #338

look to my Demo Project
https://github.com/StefaniOSApps/Example

**CLOSED**

**Comment by andreamazz** [comment] 2018-10-17 09:11
Thanks

**Closed by andreamazz** 2018-10-17 09:11 UTC
Labels: bug, help wanted
