### ISSUE TITLE
Stange white bar 

### ISSUE THREAD

**Issue by chlebta** [andreamazz/AMScrollingNavbar#137] opened 2015-06-16 16:29 UTC
Hello, This is how I'm integrating the AMScrollingNavBar : 
```
-(void)viewWillAppear:(BOOL)animated{
    [self setUseSuperview:YES];
    [self followScrollView:self.collectionView ];
    [self.collectionView reloadData];

}

- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self showNavBarAnimated:NO];
}
- (void)dealloc
{
    [self stopFollowingScrollView];
}
```

So The problem that when I set this view as the start view I got strange white bar like this one  : 
![sans titre](https://cloud.githubusercontent.com/assets/1204608/8188332/291a9d18-144d-11e5-9f70-542bf27c65b9.png)

and When I refresh this view or I don't set it as rootView It work fine and the white bar is not appearing

**Comment by andreamazz** [comment] 2015-06-16 16:30
Is your view controller a subclass of UICollectionView by any chance?

**Comment by chlebta** [comment] 2015-06-16 16:32
Yeah the parent of this view is subclass of UIcollectionView

**Comment by andreamazz** [comment] 2015-06-16 16:33
Then you should use this instead:
```
    [self setUseSuperview:YES];
```

**Comment by chlebta** [comment] 2015-06-16 16:35
But It already added added this code , check viewWillAppear first line

**Comment by andreamazz** [comment] 2015-06-16 16:36
Sorry, I didn't edit the reply in time :) I meant `NO` instead of `YES`

**Comment by chlebta** [comment] 2015-06-16 16:38
Sorry if I set it to no then I will get black bar issue 
![sans titre2](https://cloud.githubusercontent.com/assets/1204608/8188551/88ab73aa-144e-11e5-8d7c-bd41c8885a4c.png)

**Comment by andreamazz** [comment] 2015-06-16 16:45
Sorry about that, I keep mixing that property up, it was right in the first place, it should be set to `YES`.  
Getting back to the white bar... I'll see if I can reproduce the issue on the sample project.

**Comment by andreamazz** [comment] 2015-06-16 16:48
Yep, if the controller is the initial VC this happens. I'll see if I can fix it.

**Comment by chlebta** [comment] 2015-06-16 16:51
:+1:  To help you if you add this function 
```
- (BOOL)scrollViewShouldScrollToTop:(UIScrollView *)scrollView
{
    // This enables the user to scroll down the navbar by tapping the status bar.
    [self showNavbar];
    
    return YES;
}
```
and then you tap the nav bar this white space will disappear

**Comment by andreamazz** [comment] 2015-06-16 16:52
If you start following the scrollview in the `viewDidLayoutSubviews` the white space goes away, albeit the scrolling status of the collection view is wrong:
```objc
- (void)viewDidLayoutSubviews {
    [self followScrollView:self.collectionView];
}
```

**Comment by chlebta** [comment] 2015-06-16 17:02
Nope the white space is always there even with viewDidLayoutSubviews

**Comment by chlebta** [comment] 2015-06-18 10:48
@andreamazz Any other solution ?

**Comment by NicholasTD07** [comment] 2015-06-22 13:14
What constraints do you have for the collectView?

I was having this problem too. I did following things:

* Set the top bar as opacue in NavigationController
* Update constraints for the scrollView or its parent view, for example, I am using a UITableView. 

PS.
I read the document and watched the setup video, both are very helpful.

**Comment by andreamazz** [comment] 2015-06-22 13:24
Hi @chlebta 
Sorry, I have no other solutions for the moment, it seems to be working in the sample.  
I'm sorry about all the hassles in the setup, I really need to rewrite the whole thing from the ground up :/

**Comment by chlebta** [comment] 2015-06-23 09:34
@NicholasTD07  I'm creating the collectionView programmatically and I'm not setting any constraint, and I've tried to use constraint so I've added top layout constraint like this : 
```
NSLayoutConstraint *topLayoutConstraint = [NSLayoutConstraint constraintWithItem:self.collectionView
                                                                           attribute:NSLayoutAttributeTop
                                                                           relatedBy:NSLayoutRelationEqual
                                                                              toItem:self.topLayoutGuide
                                                                           attribute:NSLayoutAttributeBottom
                                                                          multiplier:1.0
                                                                            constant:0.0];
    
    [self.view addConstraint:topLayoutConstraint];
    [self followScrollView:self.collectionView usingTopConstraint:topLayoutConstraint];
```

but I got this error : 
```
Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<_UILayoutSupportConstraint:0x146d2e10 V:[_UILayoutGuide:0x146d2280(0)]>",
    "<_UILayoutSupportConstraint:0x146d3f90 V:|-(0)-[_UILayoutGuide:0x146d2280]   (Names: '|':UIView:0x146ab090 )>",
    "<NSLayoutConstraint:0x14543260 V:[_UILayoutGuide:0x146d2280]-(-2.5)-[UICollectionView:0x1526ea00]>",
    "<NSAutoresizingMaskLayoutConstraint:0x1453b530 h=--& v=--& UICollectionView:0x1526ea00.midY == + 244>",
    "<NSAutoresizingMaskLayoutConstraint:0x1453b500 h=--& v=--& V:[UICollectionView:0x1526ea00(488)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x146de9d0 h=-&- v=-&- 'UIView-Encapsulated-Layout-Top' V:|-(0)-[UIView:0x146ab090]   (Names: '|':UIViewControllerWrapperView:0x146f0000 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14543260 V:[_UILayoutGuide:0x146d2280]-(-2.5)-[UICollectionView:0x1526ea00]>
```

**Comment by andreamazz** [comment] 2015-06-23 09:36
One layout constraint is not enough, you need to provide also the bottom, left and right ones.

**Comment by NicholasTD07** [comment] 2015-06-23 09:37
In my project I have constraints for all edges, Like what @andreamazz said.

**Comment by NicholasTD07** [comment] 2015-06-23 09:39
@chlebta If you use Storyboard and only add one constraint, Xcode will prompt you in the storyboard saying that it can not figure out what to do. It needs more constraints to figure how to layout that view.

**Comment by chlebta** [comment] 2015-06-23 10:02
@NicholasTD07 I'm creating all via code, have you tried to use this library MMDrawerController library ?

**Comment by NicholasTD07** [comment] 2015-06-23 10:04
@chlebta No, sorry man. It's totally fine with AutoLayout in code. As long as you add constraints for all four edges.

**Comment by chlebta** [comment] 2015-06-23 10:07
I've added constraint for all edge some issue like this : 
```
_topLayoutConstraint = [NSLayoutConstraint constraintWithItem:self.collectionView attribute:NSLayoutAttributeTop relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeTop multiplier:1.0f constant:0.0f];
    
    [self.view addConstraint:_topLayoutConstraint];
    [self.view addConstraint:[NSLayoutConstraint constraintWithItem:self.collectionView attribute:NSLayoutAttributeBottom relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeBottom multiplier:1.0f constant:0.0f]];
    [self.view addConstraint:[NSLayoutConstraint constraintWithItem:self.collectionView attribute:NSLayoutAttributeLeading relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeLeading multiplier:1.0f constant:0.0f]];
    [self.view addConstraint:[NSLayoutConstraint constraintWithItem:self.collectionView attribute:NSLayoutAttributeTrailing relatedBy:NSLayoutRelationEqual toItem:self.view attribute:NSLayoutAttributeRight multiplier:1.0f constant:0.0f]];
``` 

I get always constraint issue : 
```
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x156d2530 V:|-(0)-[UICollectionView:0x15c2c200]   (Names: '|':UIView:0x1557d000 )>",
    "<NSLayoutConstraint:0x156d4660 UICollectionView:0x15c2c200.bottom == UIView:0x1557d000.bottom>",
    "<NSAutoresizingMaskLayoutConstraint:0x155b9cf0 h=--& v=--& V:[UICollectionView:0x15c2c200(488)]>",
    "<NSLayoutConstraint:0x155ba630 'UIView-Encapsulated-Layout-Height' V:[UIView:0x1557d000(504)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x156d4660 UICollectionView:0x15c2c200.bottom == UIView:0x1557d000.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-06-23 11:05:45.010 Free Sale[3634:423831] Successfully retrieved scores.
2015-06-23 11:05:48.013 Free Sale[3634:423831] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x156d2530 V:|-(-3)-[UICollectionView:0x15c2c200]   (Names: '|':UIView:0x1557d000 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x155b9cc0 h=--& v=--& UICollectionView:0x15c2c200.midY == + 244>",
    "<NSAutoresizingMaskLayoutConstraint:0x155b9cf0 h=--& v=--& V:[UICollectionView:0x15c2c200(488)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x155ba390 h=-&- v=-&- 'UIView-Encapsulated-Layout-Top' V:|-(0)-[UIView:0x1557d000]   (Names: '|':UIViewControllerWrapperView:0x155b6d20 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x156d2530 V:|-(-3)-[UICollectionView:0x15c2c200]   (Names: '|':UIView:0x1557d000 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by NicholasTD07** [comment] 2015-06-23 10:12
@chlebta I have little experience with adding AutoLayout by code. Sorry, couldn't help you.

**Comment by chlebta** [comment] 2015-06-23 10:15
@NicholasTD07 Me too with constraint programmatically, any way I forgot to mention that the navBar follow the scrolling but a black space is always appearing : 
![sans titre](https://cloud.githubusercontent.com/assets/1204608/8303886/2e540728-1999-11e5-9f14-0d5cd0d0797b.png)

**Comment by chlebta** [comment] 2015-06-23 10:23
I think I finally solved the issue for the moment all works fine , Ive added this code before adding constraint : 
```
    [self.collectionView setTranslatesAutoresizingMaskIntoConstraints: NO];
```

**Comment by NicholasTD07** [comment] 2015-06-23 10:25
@chlebta Good to know :+1:  If everything works fine, could you close the issue? Thanks

**Comment by chlebta** [comment] 2015-06-23 10:30
the first problem is not solved until now

**Comment by NicholasTD07** [comment] 2015-06-23 10:56
@chlebta Sorry, I forgot that. I was getting that white bar too. But it got fixed after I set top bar to non-translucent and auto layouts.

@andreamazz Is this a bug? I am asking because I see you labeld it as "bug". Isn't that collectionView in the demo working properly?

**Comment by andreamazz** [comment] 2015-06-23 11:37
It works properly in the demo, but if you make the collection view your initial view controller, the bug present itself. I solved it by starting the scroll in the `viewDidLayoutSubviews`, but this doesn't seem to work in @chlebta situation.

**Comment by NicholasTD07** [comment] 2015-06-23 22:19
@andreamazz Thank you for the detailed explanation.
@chlebta I forgot to mention that in my App, I have a navigationController as my initial view controller. I think that's why I don't have this issue. Maybe you can try using a NavControoler as your initial view controller?

**Comment by chlebta** [comment] 2015-06-24 08:19
@andreamazz  & @NicholasTD07  the white bar issue can be solved using autolayout, but without autolayout the solution using `viewDidLayoutSubviews` havn't worked for me

**Comment by NicholasTD07** [comment] 2015-06-24 08:22
@chlebta I think AutoLayout is required for AMScrollingNavbar to work properly.
@andreamazz Right?

**Comment by andreamazz** [comment] 2015-06-24 08:25
Not really, it can work without, but it goes without saying that autolayout is the preferred choice.

**Comment by NicholasTD07** [comment] 2015-06-24 08:30
@andreamazz So it's optional, but preferred. Cool.
@chlebta If autolayout can solve your issue, why not just use it? What's your concern?

**Comment by chlebta** [comment] 2015-06-24 08:50
@NicholasTD07 , I'm using it right.
Iit's just habit I used to worked always with dynamic size and I love maths so when I create something programmatically I just use some calculation formula to put it in the right position with the right size without having to use constraint and autolayout

**Comment by NicholasTD07** [comment] 2015-06-24 08:53
@chlebta I see. That sounds very cool. It's like your own autolayout. :)

**Comment by Joneze** [comment] 2015-07-01 02:59
Really cool, I also encountered the same problem, I got the answer I want from here. AutoLayout is required for AMScrollingNavbar to work properly.

**Comment by abohlsen** [comment] 2015-08-12 13:19
Hi, i had the same problem. I did some tests in the code and found a temporary fix for the issue. I changed two lines in the "- (void)updateSizingWithDelta:(CGFloat)delta" method as follow:

line 488->        frame.origin.y -= 64;
line 489->        frame.size.height = [UIScreen mainScreen].bounds.size.height - frame.origin.y;
line 490->        frame.size.height += 64;

It worked like a charm.

**Comment by andreamazz** [comment] 2015-08-16 19:30
Hi all.  
I started the rewrite of the library in swift, as a subclass of `UINavigationController`. You can find the starting code in the `swift` branch, if you want to check it out. This supports translucent navbars now, and the setup is easier, but I still have a lot of tinkering to do. Feedback is welcome.

**Comment by andreamazz** [comment] 2015-08-17 14:34
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146

**Closed by andreamazz** 2015-08-17 14:34 UTC
Labels: bug, help wanted
