### ISSUE TITLE
Black bar appears in demo app

### ISSUE THREAD

**Issue by radhakrishnapai** [andreamazz/AMScrollingNavbar#114] opened 2015-02-16 13:31 UTC
A black bar appears in certain scenarios in my app. Could'nt find the exact reason, but can be easily reproduced in the demo app. Please watch the video:

https://www.dropbox.com/s/9zixzr9p5e1hgyt/Scrolling_NavBar_Black_Bar_Issue.MOV?dl=0

**Comment by andreamazz** [comment] 2015-02-16 13:36
Hi @radhakrishnapai 
What version are you using? There's a glitch (the disappearing stuff on the navbar) that was corrected a while ago, so I'm guessing you are using an older version. Can you reproduce the issue on the latest commit?

**Comment by radhakrishnapai** [comment] 2015-02-16 13:37
That video shows the issue in the latest commit. I'll confirm again to be sure.

**Comment by andreamazz** [comment] 2015-05-24 17:28
This should be fixed (at least, I can't reproduce it on the sample app as shown in the video). Closing it for now.

**Closed by andreamazz** 2015-05-24 17:28 UTC
